import { Project } from '@/types/project';

export const MOCK_PROJECTS: Project[] = [
  // Slack Feedback workspace projects
  {
    id: 'proj-001',
    name: 'Feature Requests Analysis',
    description: 'Analyzing feature requests from Slack channels to identify top user priorities',
    status: 'Completed',
    uploadCount: 34,
    insightsCount: 127,
    lastUpdated: new Date('2024-05-15'),
    workspaceId: 'ws-001',
  },
  {
    id: 'proj-002',
    name: 'Bug Reports Sentiment',
    description: 'Sentiment analysis of bug reports and complaints from team feedback',
    status: 'Completed',
    uploadCount: 28,
    insightsCount: 94,
    lastUpdated: new Date('2024-05-12'),
    workspaceId: 'ws-001',
  },
  {
    id: 'proj-003',
    name: 'Product Feedback May',
    description: 'General product feedback collection for May sprint',
    status: 'Processing',
    uploadCount: 45,
    insightsCount: 32,
    lastUpdated: new Date('2024-05-18'),
    workspaceId: 'ws-001',
  },
  {
    id: 'proj-004',
    name: 'User Satisfaction Survey',
    description: 'Monthly user satisfaction survey responses analysis',
    status: 'Research',
    uploadCount: 12,
    insightsCount: 0,
    lastUpdated: new Date('2024-05-20'),
    workspaceId: 'ws-001',
  },
  {
    id: 'proj-005',
    name: 'Competitor Analysis',
    description: 'Feedback comparison with competitor products',
    status: 'Completed',
    uploadCount: 67,
    insightsCount: 156,
    lastUpdated: new Date('2024-05-10'),
    workspaceId: 'ws-001',
  },
  {
    id: 'proj-006',
    name: 'Onboarding Feedback',
    description: 'New user onboarding experience feedback',
    status: 'Processing',
    uploadCount: 23,
    insightsCount: 48,
    lastUpdated: new Date('2024-05-17'),
    workspaceId: 'ws-001',
  },
  {
    id: 'proj-007',
    name: 'Integration Requests',
    description: 'Customer requests for third-party integrations',
    status: 'Archived',
    uploadCount: 18,
    insightsCount: 52,
    lastUpdated: new Date('2024-04-30'),
    workspaceId: 'ws-001',
  },
  {
    id: 'proj-008',
    name: 'Performance Issues',
    description: 'User-reported performance and speed concerns',
    status: 'Completed',
    uploadCount: 31,
    insightsCount: 78,
    lastUpdated: new Date('2024-05-14'),
    workspaceId: 'ws-001',
  },

  // Customer Interviews workspace projects
  {
    id: 'proj-009',
    name: 'Enterprise Adoption Study',
    description: 'In-depth interviews with enterprise customers about adoption patterns',
    status: 'Processing',
    uploadCount: 82,
    insightsCount: 201,
    lastUpdated: new Date('2024-05-19'),
    workspaceId: 'ws-002',
  },
  {
    id: 'proj-010',
    name: 'SMB Use Cases',
    description: 'Understanding small and medium business use cases and workflows',
    status: 'Completed',
    uploadCount: 56,
    insightsCount: 134,
    lastUpdated: new Date('2024-05-16'),
    workspaceId: 'ws-002',
  },
  {
    id: 'proj-011',
    name: 'Churn Analysis Interviews',
    description: 'Exit interviews with churned customers to understand reasons',
    status: 'Research',
    uploadCount: 24,
    insightsCount: 0,
    lastUpdated: new Date('2024-05-20'),
    workspaceId: 'ws-002',
  },
  {
    id: 'proj-012',
    name: 'Pricing Perception',
    description: 'Customer interviews on pricing model and value perception',
    status: 'Completed',
    uploadCount: 38,
    insightsCount: 97,
    lastUpdated: new Date('2024-05-13'),
    workspaceId: 'ws-002',
  },
  {
    id: 'proj-013',
    name: 'Workflow Deep Dives',
    description: 'Detailed workflow and process mapping interviews',
    status: 'Processing',
    uploadCount: 71,
    insightsCount: 89,
    lastUpdated: new Date('2024-05-18'),
    workspaceId: 'ws-002',
  },
  {
    id: 'proj-014',
    name: 'Training Needs Assessment',
    description: 'Understanding customer training and onboarding needs',
    status: 'Completed',
    uploadCount: 42,
    insightsCount: 112,
    lastUpdated: new Date('2024-05-11'),
    workspaceId: 'ws-002',
  },
  {
    id: 'proj-015',
    name: 'Integration Partnerships',
    description: 'Interviews with integration partners and resellers',
    status: 'Processing',
    uploadCount: 29,
    insightsCount: 64,
    lastUpdated: new Date('2024-05-19'),
    workspaceId: 'ws-002',
  },
  {
    id: 'proj-016',
    name: 'Expansion Opportunities',
    description: 'Customer interviews on expansion and upsell opportunities',
    status: 'Completed',
    uploadCount: 48,
    insightsCount: 143,
    lastUpdated: new Date('2024-05-14'),
    workspaceId: 'ws-002',
  },
  {
    id: 'proj-017',
    name: 'Support Interaction Analysis',
    description: 'Analysis of customer support interactions and pain points',
    status: 'Completed',
    uploadCount: 93,
    insightsCount: 267,
    lastUpdated: new Date('2024-05-15'),
    workspaceId: 'ws-002',
  },
  {
    id: 'proj-018',
    name: 'Account Health Deep Dive',
    description: 'Understanding account health metrics and customer satisfaction',
    status: 'Processing',
    uploadCount: 55,
    insightsCount: 76,
    lastUpdated: new Date('2024-05-17'),
    workspaceId: 'ws-002',
  },
  {
    id: 'proj-019',
    name: 'Buyer Personas',
    description: 'Comprehensive buyer persona development interviews',
    status: 'Completed',
    uploadCount: 67,
    insightsCount: 189,
    lastUpdated: new Date('2024-05-12'),
    workspaceId: 'ws-002',
  },
  {
    id: 'proj-020',
    name: 'Industry Benchmarking',
    description: 'Benchmarking against industry standards and competitors',
    status: 'Research',
    uploadCount: 15,
    insightsCount: 0,
    lastUpdated: new Date('2024-05-20'),
    workspaceId: 'ws-002',
  },

  // Mobile Beta workspace projects
  {
    id: 'proj-021',
    name: 'iOS Usability Testing',
    description: 'Usability testing sessions for iOS mobile app',
    status: 'Processing',
    uploadCount: 38,
    insightsCount: 102,
    lastUpdated: new Date('2024-05-18'),
    workspaceId: 'ws-003',
  },
  {
    id: 'proj-022',
    name: 'Android Performance',
    description: 'Performance testing and user feedback for Android app',
    status: 'Completed',
    uploadCount: 44,
    insightsCount: 118,
    lastUpdated: new Date('2024-05-15'),
    workspaceId: 'ws-003',
  },
  {
    id: 'proj-023',
    name: 'Mobile Navigation Redesign',
    description: 'Testing new mobile navigation UI with beta users',
    status: 'Research',
    uploadCount: 19,
    insightsCount: 0,
    lastUpdated: new Date('2024-05-20'),
    workspaceId: 'ws-003',
  },
  {
    id: 'proj-024',
    name: 'Offline Mode Testing',
    description: 'Beta testing offline functionality and sync behavior',
    status: 'Processing',
    uploadCount: 28,
    insightsCount: 65,
    lastUpdated: new Date('2024-05-19'),
    workspaceId: 'ws-003',
  },
  {
    id: 'proj-025',
    name: 'Mobile Accessibility',
    description: 'Accessibility testing with diverse user groups',
    status: 'Completed',
    uploadCount: 22,
    insightsCount: 76,
    lastUpdated: new Date('2024-05-16'),
    workspaceId: 'ws-003',
  },

  // Q2 User Research workspace projects
  {
    id: 'proj-026',
    name: 'Q2 General Survey',
    description: 'Quarterly general user satisfaction and NPS survey',
    status: 'Processing',
    uploadCount: 234,
    insightsCount: 456,
    lastUpdated: new Date('2024-05-19'),
    workspaceId: 'ws-004',
  },
  {
    id: 'proj-027',
    name: 'Focus Group Discussions',
    description: 'Moderated focus groups on product roadmap priorities',
    status: 'Completed',
    uploadCount: 78,
    insightsCount: 234,
    lastUpdated: new Date('2024-05-17'),
    workspaceId: 'ws-004',
  },
  {
    id: 'proj-028',
    name: 'Ethnographic Research',
    description: 'Long-term ethnographic study of user behaviors and contexts',
    status: 'Research',
    uploadCount: 45,
    insightsCount: 0,
    lastUpdated: new Date('2024-05-20'),
    workspaceId: 'ws-004',
  },
  {
    id: 'proj-029',
    name: 'Market Sizing Study',
    description: 'Market analysis and sizing for expansion planning',
    status: 'Processing',
    uploadCount: 156,
    insightsCount: 203,
    lastUpdated: new Date('2024-05-18'),
    workspaceId: 'ws-004',
  },
  {
    id: 'proj-030',
    name: 'Segmentation Analysis',
    description: 'User segmentation and persona refinement',
    status: 'Completed',
    uploadCount: 89,
    insightsCount: 267,
    lastUpdated: new Date('2024-05-14'),
    workspaceId: 'ws-004',
  },
  {
    id: 'proj-031',
    name: 'Feature Importance Matrix',
    description: 'Prioritization and importance mapping of features',
    status: 'Completed',
    uploadCount: 67,
    insightsCount: 145,
    lastUpdated: new Date('2024-05-16'),
    workspaceId: 'ws-004',
  },
  {
    id: 'proj-032',
    name: 'Usage Patterns Analysis',
    description: 'Behavioral analysis of product usage patterns',
    status: 'Processing',
    uploadCount: 123,
    insightsCount: 178,
    lastUpdated: new Date('2024-05-19'),
    workspaceId: 'ws-004',
  },
  {
    id: 'proj-033',
    name: 'Retention Drivers Study',
    description: 'Identifying key drivers of user retention and loyalty',
    status: 'Completed',
    uploadCount: 102,
    insightsCount: 234,
    lastUpdated: new Date('2024-05-13'),
    workspaceId: 'ws-004',
  },
  {
    id: 'proj-034',
    name: 'Activation Improvement',
    description: 'Research on improving new user activation rates',
    status: 'Research',
    uploadCount: 38,
    insightsCount: 0,
    lastUpdated: new Date('2024-05-20'),
    workspaceId: 'ws-004',
  },
  {
    id: 'proj-035',
    name: 'Competitive Benchmarking',
    description: 'Detailed competitor feature and UX comparison',
    status: 'Completed',
    uploadCount: 145,
    insightsCount: 312,
    lastUpdated: new Date('2024-05-15'),
    workspaceId: 'ws-004',
  },
  {
    id: 'proj-036',
    name: 'Messaging & Positioning',
    description: 'Testing messaging and market positioning concepts',
    status: 'Processing',
    uploadCount: 67,
    insightsCount: 123,
    lastUpdated: new Date('2024-05-18'),
    workspaceId: 'ws-004',
  },
  {
    id: 'proj-037',
    name: 'Trend Analysis Q2',
    description: 'Market trends and industry analysis for Q2',
    status: 'Completed',
    uploadCount: 98,
    insightsCount: 189,
    lastUpdated: new Date('2024-05-16'),
    workspaceId: 'ws-004',
  },
  {
    id: 'proj-038',
    name: 'Customer Success Stories',
    description: 'Collection and analysis of success stories and case studies',
    status: 'Processing',
    uploadCount: 52,
    insightsCount: 87,
    lastUpdated: new Date('2024-05-19'),
    workspaceId: 'ws-004',
  },
  {
    id: 'proj-039',
    name: 'Expansion Markets',
    description: 'Research on potential new markets for expansion',
    status: 'Research',
    uploadCount: 23,
    insightsCount: 0,
    lastUpdated: new Date('2024-05-20'),
    workspaceId: 'ws-004',
  },
  {
    id: 'proj-040',
    name: 'Product Roadmap Validation',
    description: 'Validating proposed product roadmap with users',
    status: 'Completed',
    uploadCount: 134,
    insightsCount: 298,
    lastUpdated: new Date('2024-05-14'),
    workspaceId: 'ws-004',
  },

  // Enterprise Clients workspace projects
  {
    id: 'proj-041',
    name: 'Account Management Review',
    description: 'Review of account management processes with enterprise clients',
    status: 'Completed',
    uploadCount: 41,
    insightsCount: 98,
    lastUpdated: new Date('2024-05-15'),
    workspaceId: 'ws-005',
  },
  {
    id: 'proj-042',
    name: 'Implementation Success',
    description: 'Analysis of successful implementations and best practices',
    status: 'Processing',
    uploadCount: 38,
    insightsCount: 67,
    lastUpdated: new Date('2024-05-18'),
    workspaceId: 'ws-005',
  },
  {
    id: 'proj-043',
    name: 'Enterprise Feature Requests',
    description: 'Consolidated feature requests from enterprise segment',
    status: 'Completed',
    uploadCount: 29,
    insightsCount: 76,
    lastUpdated: new Date('2024-05-16'),
    workspaceId: 'ws-005',
  },
  {
    id: 'proj-044',
    name: 'Support Quality Review',
    description: 'Enterprise support quality and satisfaction analysis',
    status: 'Processing',
    uploadCount: 33,
    insightsCount: 54,
    lastUpdated: new Date('2024-05-19'),
    workspaceId: 'ws-005',
  },
  {
    id: 'proj-045',
    name: 'ROI Impact Study',
    description: 'Measuring and validating ROI impact for enterprise customers',
    status: 'Research',
    uploadCount: 18,
    insightsCount: 0,
    lastUpdated: new Date('2024-05-20'),
    workspaceId: 'ws-005',
  },
  {
    id: 'proj-046',
    name: 'Multi-team Collaboration',
    description: 'Research on multi-team collaboration features and workflows',
    status: 'Completed',
    uploadCount: 44,
    insightsCount: 112,
    lastUpdated: new Date('2024-05-13'),
    workspaceId: 'ws-005',
  },
];
